### ISSUE TITLE
pathlib2 を使うメリットが薄いのでは?

### ISSUE THREAD

**Issue by ogyogy** [okojomoeko/get-git-repository#2]
pathlib2 は pathlib を Python2.x で使うためのライブラリだが、下記の理由から pathlib2 を使うメリットが薄い気がします。

- setup.py で```python_requires='>=3.7'```としている
- pathlib は Python>=3.4 で標準
- pathlib2 を使うことにより依存関係が増える

**Comment by okojomoeko** [comment]
朝起きたら大量のメールが着ててgithub使いこなしてる感出てる
とりあえず修正して閉じませう
